version: '3.1'

services:

  oracle:
    image: 'gvenzl/oracle-free:latest'
    environment:
      - 'ORACLE_RANDOM_PASSWORD=true'
      - 'APP_USER=PERSONS_DB'
      - 'APP_USER_PASSWORD=Lider0ne'
    ports:
      - 1520:1521

  adminer:
    container_name: mysql-8.0.36
    image: adminer:4.8.0-standalone
    restart: always
    ports:
      - 9080:8080
